name: Run Test Suite

on:
  push:
    paths-ignore:
    - 'images/**'
    - '**.md'


permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  run-tests:
    name: Test Suite
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    
    defaults:
      run:
        working-directory: .
    
    steps:
    - name: Checkout files
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install chromium-driver
        pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run Tests
      run: |
        coverage run -m pytest tests --headless
        coverage report -m
