name: Run Test Suite

on:
  push:
    branches:
    - master       # Only run tests on master
    paths-ignore:
    - 'images/**'  # Ignore changes in images directory
    - '**.md'      # Ignore documentation changes

# Set permissions for accessing repository 
permissions:
  contents: read
    
env:
  PYTHON_VERSION: '3.12'

jobs:
  run-tests:
    name: Test Suite
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .
    
    steps:
    - name: Checkout files
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install chromium-driver
        pip install --upgrade pip
        pip install -r requirements-dev.txt

    # Run tests with coverage reporting
    - name: Run Tests
      run: |
        coverage run -m pytest tests --headless
        coverage report -m
